name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.13.4
      - name: Install dependencies
        run: pnpm --filter ./packages/core install
      - name: Run tests and collect coverage
        run: pnpm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.COV_TOKEN }}
          name: codecov-coverage
          flags: unittests